---
name: CI
on: null
push: null
branches:
  - main
pull_request:
  branches:
    - main
workflow_dispatch: null
permissions: null
id-token: write
contents: read
build: null
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - name: Retrieve secret from Vault
id: secretdata
uses: hashicorp/vault-action@v2.4.0
with: null
method: jwt
url: https://127.0.0.1:8200
role: mygithubproject-productionrole2
namespace: root
secrets: kv/data/secrets/mygithubproject/secret1 secretvalue |
