name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Install Vault CLI
      - name: Install Vault CLI
        run: |
          sudo apt-get update && sudo apt-get install -y vault

      # Step 3: Retrieve GitHub OIDC token (this is automatic for GitHub Actions)
      - name: Retrieve GitHub OIDC token
        id: oidc-token
        run: echo "OIDC_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      # Step 4: Log in to Vault using JWT and a custom auth path
      - name: Vault Login using custom JWT Auth Path
        env:
          VAULT_ADDR: https://xxxyyy.net:8200
          VAULT_NAMESPACE: root
          GITHUB_OIDC_TOKEN: ${{ steps.oidc-token.outputs.oidc-token }}
        run: |
          vault login -method=mycustom_github_jwt_engine \
            role=mygithubproject-productionrole2 \
            jwt=$GITHUB_OIDC_TOKEN

      # Step 5: Retrieve secrets from Vault
      - name: Retrieve secret from Vault
        id: secretdata
        run: |
          VAULT_SECRET=$(vault kv get -field=secretvalue kv/data/secrets/mygithubproject/secret1)
          echo "MY_SECRET=$VAULT_SECRET" >> $GITHUB_ENV

      # Step 6: Use secret from Vault
      - name: Use secret from Vault
        run: |
          echo "Retrieved secret: ${{ env.MY_SECRET }}"
